### PR TITLE
Raml1.0

### PR DESCRIPTION
**Pull request by petrochenko-pavel-a**
Very initial version supporting raml1.0->jaxrs.

### CODE REVIEW

**Comment by petrochenko-pavel-a** [comment]
@sichvoge @mutsys

may you please review this contribution. It adds initial support for RAML 1.0 ->JAX RS.

**Comment by sichvoge** [comment]
Hi Pavel. Thanks for the PR. I have let others know to test your PR and give you feedback. Hope that will help you!

**Comment by BackendButters** [comment]
would be awesome to have RAML 1.0 support!

**Comment by sichvoge** [comment]
Hi @BackendButters did you see https://github.com/mulesoft/raml-for-jax-rs/milestone/1. We are actively working on it. Probably not merging this PR directly, since we want to have some overall improvements to the base implementation to build the foundation for RAML 1.0.

**Pull request closed without merging**
